### ISSUE TITLE
Quiz doesn't resume in incognito window

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#116]
Start taking the quiz, then close the window, and open it up in an incognito window. The quiz won't resume from where it left. It would just get stuck, not showing anything, and not saying anything. Console shows this error:

```
angular.min.js:102TypeError: Cannot read property 'token' of null
    at candidateController.checkValidity (https://gru.dgraph.io/app/components/candidate/candidateController.js?v=20161105-1:40:17)
    at new candidateController (https://gru.dgraph.io/app/components/candidate/candidateController.js?v=20161105-1:13:43)
    at Object.e [as invoke] (https://gru.dgraph.io/assets/lib/js/angular.min.js:36:315)
    at x.instance (https://gru.dgraph.io/assets/lib/js/angular.min.js:75:451)
    at https://gru.dgraph.io/assets/lib/js/angular.min.js:58:474
    at s (https://gru.dgraph.io/assets/lib/js/angular.min.js:7:408)
    at v (https://gru.dgraph.io/assets/lib/js/angular.min.js:58:458)
    at g (https://gru.dgraph.io/assets/lib/js/angular.min.js:51:299)
    at https://gru.dgraph.io/assets/lib/js/angular.min.js:50:413
    at https://gru.dgraph.io/assets/lib/js/angular-ui-router.min.js:7:23478 <main data-ui-view="" class="mdl-layout__content ng-scope">
```

**Comment by pawanrawal** [comment]
Fixed.
